export const ROLES = {
  CITIZEN: 'CITIZEN',
  CONTROL_ROOM_ADMIN: 'CONTROL_ROOM_ADMIN',
  STATION_HEAD: 'STATION_HEAD',
  INVESTIGATING_OFFICER: 'INVESTIGATING_OFFICER',
  FIELD_OFFICER: 'FIELD_OFFICER'
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED'
};

export const DUTY_STATUS = {
  ON_DUTY: 'ON_DUTY',
  OFF_DUTY: 'OFF_DUTY',
  BUSY: 'BUSY',
  AVAILABLE: 'AVAILABLE'
};

export const OFFICER_RANKS = {
  COMMISSIONER: 'COMMISSIONER',
  INSPECTOR: 'INSPECTOR',
  SUB_INSPECTOR: 'SUB_INSPECTOR',
  ASSISTANT_SUB_INSPECTOR: 'ASSISTANT_SUB_INSPECTOR',
  HEAD_CONSTABLE: 'HEAD_CONSTABLE',
  CONSTABLE: 'CONSTABLE'
};

export const STATION_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};

export const CRIME_TYPES = {
  THEFT: 'THEFT',
  ASSAULT: 'ASSAULT',
  FRAUD: 'FRAUD',
  CYBER_CRIME: 'CYBER_CRIME',
  HARASSMENT: 'HARASSMENT',
  MISSING_PERSON: 'MISSING_PERSON',
  VANDALISM: 'VANDALISM',
  TRAFFIC: 'TRAFFIC',
  OTHER: 'OTHER'
};

export const COMPLAINT_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

export const COMPLAINT_STATUS = {
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  ASSIGNED: 'ASSIGNED',
  INVESTIGATION: 'INVESTIGATION',
  FIR_REGISTERED: 'FIR_REGISTERED',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED'
};

export const FIR_STATUS = {
  REGISTERED: 'REGISTERED',
  UNDER_INVESTIGATION: 'UNDER_INVESTIGATION',
  CLOSED: 'CLOSED'
};

export const SOS_STATUS = {
  ACTIVE: 'ACTIVE',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  DISPATCHED: 'DISPATCHED',
  RESOLVED: 'RESOLVED',
  ESCALATED: 'ESCALATED'
};

export const ANNOUNCEMENT_TYPES = {
  CRIME_ALERT: 'CRIME_ALERT',
  ROAD_ALERT: 'ROAD_ALERT',
  MISSING_PERSON: 'MISSING_PERSON',
  PUBLIC_SAFETY: 'PUBLIC_SAFETY',
  GENERAL: 'GENERAL'
};

export const ANNOUNCEMENT_SEVERITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

export const ANNOUNCEMENT_STATUS = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  ARCHIVED: 'ARCHIVED'
};

export const PATROL_STATUS = {
  PLANNED: 'PLANNED',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

export const NOTIFICATION_TYPES = {
  COMPLAINT: 'COMPLAINT',
  FIR: 'FIR',
  SOS: 'SOS',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  PATROL: 'PATROL',
  SYSTEM: 'SYSTEM'
};
